-- 6. States table
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa ;
CREATE TABLE IF NOT EXISTS hbtn_0d_usa.stats (
    id INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY (id),
    name VARCHAR(256) NOT NULL
);