name: Change File Permissions

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  change-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Change file permissions
      run: chmod -R +x .

    - name: Commit changes
      run: |
        git config --global user.name "maysara.nagy@gmail.com"
        git config --global user.email "Maysara-nagy"
        git add .
        git commit -m "Set executable bit for all files"

    - name: Push changesa
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
