name: Change File Permissions

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  change-permissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Change file permissions
      run: chmod -R +x .
